service: serverless-todo-app

provider:
  name: aws
  runtime: nodejs14.x

functions:
  createTodo:
    handler: handler.create
    events:
      - http:
          path: todos
          method: post
  getTodos:
    handler: handler.getAll
    events:
      - http:
          path: todos
          method: get
  deleteTodo:
    handler: handler.delete
    events:
      - http:
          path: todos/{id}
          method: delete